#!/bin/bash

# bash_profile

declare -a mv files=(
    $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
    $HOME/.nvm/nvm.sh
    $HOME/.dotfiles/bash/bash_config # Configuration
    $HOME/.dotfiles/bash/bash_aliases # Aliases
    $HOME/.dotfiles/bash/functions/* # Functions
    $HOME/.dotfiles/bash/z/z.sh # Z the nimble frecency based file jumper
    $HOME/.dotfiles/bash/bash_prompt # Custom bash prompt
    $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    $HOME/.dotfiles/bash/bash_paths # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# Seems to be default location on Debian
bash_completion_path="/etc/bash_completion"

# Source Bash completion
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi
