#!/bin/bash

# inputrc

# Use case-insensitive TAB autocompletion
set completion-ignore-case on

# Make TAB cycle through possible completions
"\t": menu-complete

# Use the string that has already been typed as the prefix for searching
# through commands (i.e. more intelligent Up/Down behavior)
"\e[B": history-search-forward
"\e[A": history-search-backward

# Ctrl-[left|right]-arrow word jumping
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
